# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('name_id', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po_supplier', models.CharField(max_length=50, unique=True)),
                ('po_customer', models.CharField(max_length=50, unique=True)),
                ('ready_date', models.DateTimeField()),
                ('shipment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'PO Open'), ('completed', 'PO Closed')], default='open', max_length=10)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.Customer')),
            ],
            options={
                'verbose_name': 'PO Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('collection', models.CharField(blank=True, max_length=150)),
                ('brand_name', models.CharField(blank=True, max_length=150)),
                ('prod_price', models.IntegerField(default=0)),
                ('pub_price', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Product',
            },
        ),
        migrations.CreateModel(
            name='ProductPo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_order', models.IntegerField()),
                ('qty_shipped', models.IntegerField(default=0)),
                ('qty_balance', models.IntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.Product')),
                ('po_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.PoOrder')),
            ],
            options={
                'verbose_name': 'Product PO',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('name_id', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.Supplier', to_field='name_id'),
        ),
    ]
