# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpo',
            old_name='qty_balance',
            new_name='qty_ready',
        ),
    ]
