# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20190111_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/noimage.jpg', upload_to='images'),
        ),
    ]
