# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['code'], 'verbose_name': 'Master Product'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pub_price',
            new_name='retail_price',
        ),
    ]
