# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_product_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='no',
            field=models.CharField(max_length=100),
        ),
    ]
