# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20190119_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='brand_name',
            field=models.CharField(blank=True, help_text='If no brand, could be empty', max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check if active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_id',
            field=models.CharField(help_text='All lowercase and no space', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='Unique product code with size and color codes, example: MSN001_BLK_XL', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check if active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Product name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='no',
            field=models.CharField(help_text='Unique master code for all sizes and colors, example: MSN001', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.IntegerField(default=0, help_text='Production price'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check if active'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name_id',
            field=models.CharField(help_text='All lowercase and no space', max_length=200, unique=True),
        ),
    ]
