# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_auto_20190119_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(unique=True),
        ),
    ]
