# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_auto_20190119_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
