# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masterdata.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='send_to_be_shipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='po_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.PoOrder'),
        ),
    ]
